### ISSUE TITLE
Subtasks not part of the analytics reports

### ISSUE THREAD

**Issue by ibedon** [aljawaid/KanboardCSS#2]
Hello:

I would like to know if there is a plugin or update available that helps to have a more granular report for analytics, specially having the subtasks will be a great help.

Regards,
Isabel

**Comment by ThomasTJdev** [comment]
Hi @ibedon 
The plugin is not maintained anymore. Sorry.

**Comment by ibedon** [comment]
Hi Thomas: is there any substitute of it?

On Jun 4, 2018 4:03 PM, "Thomas T. Jarløv" <notifications@github.com> wrote:

Hi @ibedon<https://github.com/ibedon>
The plugin is not maintained anymore. Sorry.

**Comment by ThomasTJdev** [comment]
Hi @ibedon  
I don't know. I'm not using Kanboard anymore.

**Comment by aljawaid** [comment]
Hi @ThomasTJdev would you be okay if we used the current css to build on a newer plugin for recent versions?

**Comment by ThomasTJdev** [comment]
Hi @aljawaid 
Thanks for asking. That is okay - you can use it with no restrictions. You may also take ownership of the repo.
If you create a new repo, please post a link here, which I can add in the readme.

**Comment by ThomasTJdev** [comment]
Hi @aljawaid 
I can not transfer ownership, when you have forked repo with the same name: `aljawaid/KanboardCSS already exists`

**Comment by aljawaid** [comment]
Hi @ThomasTJdev I have deleted my forked repo, please try again.
