### ISSUE TITLE
collapsed column

### ISSUE THREAD

**Issue by TimoStahl** [aljawaid/KanboardCSS#7]
Hey,
first of all, I like the style of this plugin :)

Unfortunately a hidden column seems a bit glitchy and is hard to reopen again.
In addition the number shows only the number of cards in the first swimlane. It might be hidden if only the first swimlane has a header line.

![image](https://user-images.githubusercontent.com/1961634/60593341-cfea1c80-9da2-11e9-8685-2e9b68fa29b7.png)

**Comment by BlueTeck** [comment]
https://github.com/aljawaid/KanboardCSS/blob/master/kanboardcss.css#L445
